
package AgendaEletronica;

import javax.swing.JOptionPane;

public class JanelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName());
    private Agenda agenda;
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        agenda = new Agenda();
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCpf = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        listaButtom = new javax.swing.JButton();
        saveButtom1 = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGENDA DE CONTATOS");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 20));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TELEFONE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        campoNome.setBackground(new java.awt.Color(204, 204, 255));
        campoNome.setForeground(new java.awt.Color(102, 0, 102));
        campoNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        campoNome.setCaretColor(new java.awt.Color(153, 0, 153));
        campoNome.setDisabledTextColor(new java.awt.Color(102, 0, 102));
        campoNome.addActionListener(this::campoNomeActionPerformed);
        getContentPane().add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 20));

        campoCpf.setBackground(new java.awt.Color(204, 204, 255));
        campoCpf.setForeground(new java.awt.Color(102, 0, 102));
        campoCpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoCpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        campoCpf.setCaretColor(new java.awt.Color(153, 0, 153));
        campoCpf.setDisabledTextColor(new java.awt.Color(102, 0, 102));
        campoCpf.addActionListener(this::campoCpfActionPerformed);
        getContentPane().add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 20));

        campoTelefone.setBackground(new java.awt.Color(204, 204, 255));
        campoTelefone.setForeground(new java.awt.Color(102, 0, 102));
        campoTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        campoTelefone.setCaretColor(new java.awt.Color(153, 0, 153));
        campoTelefone.setDisabledTextColor(new java.awt.Color(102, 0, 102));
        campoTelefone.addActionListener(this::campoTelefoneActionPerformed);
        getContentPane().add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, 20));

        campoEmail.setBackground(new java.awt.Color(204, 204, 255));
        campoEmail.setForeground(new java.awt.Color(102, 0, 102));
        campoEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        campoEmail.setCaretColor(new java.awt.Color(153, 0, 153));
        campoEmail.setDisabledTextColor(new java.awt.Color(102, 0, 102));
        campoEmail.addActionListener(this::campoEmailActionPerformed);
        getContentPane().add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 20));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Adicione seus contatos favoritos aqui!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NOME:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("E- MAIL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        listaButtom.setBackground(new java.awt.Color(204, 204, 255));
        listaButtom.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        listaButtom.setForeground(new java.awt.Color(153, 0, 153));
        listaButtom.setText("Vizualizar Contatos ");
        listaButtom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        listaButtom.addActionListener(this::listaButtomActionPerformed);
        getContentPane().add(listaButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 20));

        saveButtom1.setBackground(new java.awt.Color(204, 204, 255));
        saveButtom1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        saveButtom1.setForeground(new java.awt.Color(153, 0, 153));
        saveButtom1.setText("Adcionar");
        saveButtom1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153)));
        saveButtom1.addActionListener(this::saveButtom1ActionPerformed);
        getContentPane().add(saveButtom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed

        
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
       
    }//GEN-LAST:event_campoCpfActionPerformed

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed
       
    }//GEN-LAST:event_campoTelefoneActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
       
    }//GEN-LAST:event_campoEmailActionPerformed

    private void listaButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaButtomActionPerformed

    TabelaContatos janela = new TabelaContatos(agenda);
    janela.carregarTabela(agenda);
    janela.setVisible(true);
    }//GEN-LAST:event_listaButtomActionPerformed

   
    private void saveButtom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtom1ActionPerformed
      String nome= campoNome.getText();
      String cpf= campoCpf.getText();
      String email= campoEmail.getText();
      String telefone= campoTelefone.getText();
      
      if (nome.isEmpty()||
          cpf.isEmpty()||
          email.isEmpty()||
          telefone.isEmpty()){
            JOptionPane.showMessageDialog(this,"Todos os campos precisam ser preenchidos");
            return;
      }
      
      Contato conato1= new Contato(cpf, nome, email, telefone);
      agenda.adicionar(conato1);
      
      JOptionPane.showMessageDialog(this,"Contato adicionado!");
      limparCampos();
    }   
    
     private void  limparCampos(){
     for (java.awt.Component contato : getContentPane().getComponents()){
         if (contato instanceof javax.swing.JTextField){
             /* esta regra abaixo serve para o java tratar o Component "contato"
             como um JTextField, para não ocorrer erros, pois, 
             nem todo Component tem setText() e nesta regra passamos contato como 
             JTextField com o cast
             */
                ((javax.swing.JTextField) contato).setText("");
         
         }
     
        }
     
     }
    

    /**
     *  // TODO add your handling code here:
    }//GEN-LAST:event_saveButtom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton listaButtom;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JButton saveButtom1;
    // End of variables declaration//GEN-END:variables

}
