/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgendaEletronica;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Berli
 */
public class TabelaContatos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabelaContatos.class.getName());
    private Agenda agenda;
    
    /**
     * Creates new form TabelaContatos
     */
    public TabelaContatos(Agenda agenda) {
        initComponents();
        this.agenda=agenda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaContatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backButtom = new javax.swing.JButton();
        deleteButtom = new javax.swing.JButton();
        searchButtom = new javax.swing.JButton();
        busca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        updateButtom = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        listaContatos.setBackground(new java.awt.Color(204, 204, 255));
        listaContatos.setForeground(new java.awt.Color(102, 0, 102));
        listaContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "E - mail", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaContatos.setGridColor(new java.awt.Color(153, 153, 255));
        listaContatos.setSelectionBackground(new java.awt.Color(153, 153, 255));
        listaContatos.setSelectionForeground(new java.awt.Color(153, 0, 153));
        listaContatos.setShowGrid(true);
        jScrollPane1.setViewportView(listaContatos);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE CONTATOS");

        backButtom.setBackground(new java.awt.Color(204, 204, 255));
        backButtom.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        backButtom.setForeground(new java.awt.Color(153, 0, 153));
        backButtom.setText("Voltar");
        backButtom.addActionListener(this::backButtomActionPerformed);

        deleteButtom.setBackground(new java.awt.Color(204, 204, 255));
        deleteButtom.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        deleteButtom.setForeground(new java.awt.Color(153, 0, 153));
        deleteButtom.setText("Remover");
        deleteButtom.addActionListener(this::deleteButtomActionPerformed);

        searchButtom.setBackground(new java.awt.Color(204, 204, 255));
        searchButtom.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        searchButtom.setForeground(new java.awt.Color(153, 0, 153));
        searchButtom.setText("Pesquisar");
        searchButtom.addActionListener(this::searchButtomActionPerformed);

        busca.addActionListener(this::buscaActionPerformed);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Busca:");

        updateButtom.setBackground(new java.awt.Color(204, 204, 255));
        updateButtom.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        updateButtom.setForeground(new java.awt.Color(153, 0, 153));
        updateButtom.setText("Refresh");
        updateButtom.addActionListener(this::updateButtomActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButtom)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(deleteButtom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButtom)
                .addGap(40, 40, 40)
                .addComponent(backButtom)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButtom)
                    .addComponent(deleteButtom)
                    .addComponent(updateButtom))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    public void carregarTabela(Agenda agenda){
    DefaultTableModel modelo = (DefaultTableModel) listaContatos.getModel();
    modelo.setRowCount(0);//LIMPA a tabela
    
       System.out.println("Quantidade de contatos: " + agenda.getContatos().size());
    
    for (Contato contato : agenda.getContatos()){
        
        modelo.addRow(new Object []{
        
            contato.getCpf(),
            contato.getNome(),
            contato.getEmail(),
            contato.getTelefone(),
        
            });
        }
    }
  
    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        this.setVisible(false);
        
      
    }//GEN-LAST:event_backButtomActionPerformed

    private void deleteButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtomActionPerformed
         
         int linha = listaContatos.getSelectedRow();

    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "selecione um contato");
        return;
    }

    int opcao = JOptionPane.showConfirmDialog(
        this,
        "tem certeza?",
        "confirmação",
        JOptionPane.YES_NO_OPTION
    );

    if (opcao == JOptionPane.YES_OPTION) {
        agenda.remover(linha);
        carregarTabela(agenda);
    }
    }//GEN-LAST:event_deleteButtomActionPerformed

    private void searchButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtomActionPerformed
        String textoBusca = busca.getText();
       
        
        if(textoBusca.isEmpty()){
             listaContatos.setRowSorter(null);
             JOptionPane.showMessageDialog(this,"preencha o campo de busca");
             return;
        } else{
            
        DefaultTableModel modelo = (DefaultTableModel) listaContatos.getModel();
        TableRowSorter<DefaultTableModel> sort = new TableRowSorter<>(modelo);
        
        
        listaContatos.setRowSorter(sort);
            sort.setRowFilter(RowFilter.regexFilter("(?i)"+ textoBusca, 0,1,2,3,9) );
        }
     
    }//GEN-LAST:event_searchButtomActionPerformed

    private void buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaActionPerformed
        
     
    }//GEN-LAST:event_buscaActionPerformed

    private void updateButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtomActionPerformed
        carregarTabela(agenda);
        JOptionPane.showMessageDialog(this,"Lista Atualizada");
        listaContatos.setRowSorter(null);

    }//GEN-LAST:event_updateButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtom;
    private javax.swing.JTextField busca;
    private javax.swing.JButton deleteButtom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaContatos;
    private javax.swing.JButton searchButtom;
    private javax.swing.JButton updateButtom;
    // End of variables declaration//GEN-END:variables
}
